project:
  type: website
  output-dir: docs

website:
  title: "講義ノート"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hamiltonian_lattice/index.qmd
        text: ハミルトニアン形式による格子ゲージ理論

format:
  html:
    toc: true
    number-sections: true
