project:
  type: website
  output-dir: docs

  pre-render:
    - quarto render hamiltonian_lattice

  post-render:
    - mkdir -p docs/hamiltonian_lattice
    - rsync -a hamiltonian_lattice/_book/ docs/hamiltonian_lattice/

website:
  title: "講義ノート"
  navbar:
    search: true
    left:
      - href: index.html
        text: Home
      - href: hamiltonian_lattice/index.html
        text: ハミルトニアン形式による格子ゲージ理論
  sidebar:
    style: "floating"

format:
  html:
    toc: true
    number-sections: true