project:
  type: website
  output-dir: docs

  render:
    - index.qmd
    - "!hamiltonian_lattice/**"

website:
  title: "講義ノート"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: hamiltonian_lattice/index.html
        text: ハミルトニアン形式による格子ゲージ理論

sidebar:
  background: light
  style: floating

execute:
  cache: true
  freeze: auto

format:
  html:
    theme: flatly
    toc: true
    number-sections: true