project:
  type: book

book:
  title: "格子ゲージ理論 講義ノート"
  chapters:
    - index.qmd
    - 01-basics.qmd

format:
  html:
    toc: true
    number-sections: true
  pdf:
    documentclass: book
    number-sections: true
