\newcommand{\sthreer}{r}
\newcommand{\sthreerr}{r^2}
\newcommand{\sthreera}{s_1}
\newcommand{\sthreerb}{s_2}
\newcommand{\sthreerc}{s_3}

#　群論基礎 {#sec-group_theory}

::: definition
**群の定義**

群 $(G,e,\circ)$ とは，集合 $G$ に積 $\circ:G\times G\to G$ が定まっていて，以下の条件を満たすものである：

1. （単位元の存在）$e\in G$ が存在して，すべての $g\in G$ に対して $eg=ge=g$ となる．
2. （逆元の存在）すべての $g\in G$ に対して，$g^{-1}\in G$ が存在し，$gg^{-1}=g^{-1}g=e$ となる．
3. （結合法則）すべての $g,g',g''\in G$ に対して，$(g\circ g')\circ g''=g\circ(g'\circ g'')$ が成り立つ．
:::

任意の $G$ の元 $g,g'$ について，$gg'=g'g$ が成り立つとき，群 $G$ は可換群であるという．

::: example
**$\mathbb{Z}_2$群**

要素が $2$ つからなる群は，$\mathbb{Z}_2$ 群と呼ばれる可換群となる．  
$G=\{1,-1\}$, $\circ = \times$, $e=1$ に取ると群になっている．
:::

場の量子論で特に重要になる群は，ユニタリー群である．$\mathrm{U}(N)$群は，
複素 $N$ 次元ベクトル $\bm{z}=(z_1,\cdots z_N)^T$ の内積 $\bm{z}^\dag z$ を不変に保つ変換
$$
\bm{z}\to \bm{z}'= g \bm{z}
$$
である．内積を保つ条件から $g^\dag g=1$ となる．つまり $g^\dag = g^{-1}$ である．
$g$ は $N\times N$ 行列であるので，行列の積，結合則が成り立つ．これらにより群になっていることがわかる．

特に，すべての $g$ の行列式が $1$ の時($\det g=1$)，特殊ユニタリー群といい，$\mathrm{SU}(N)$ と書く．
以下では，$\mathrm{SU}(N)$群を考える．
$\mathrm{SU}(N)$ の元は，

$$
  g = e^{\ri\theta^i T_i}
$$

の指数表示を持つことが知られている．
ここで，$T_i$ は，$N\times N$ の行列で，$g$ は，形式的に，

$$
  U=\sum_{n=0}^\infty \frac{1}{n!}(\ri \theta^iT_i)^n
$$

で定義される．
単位元の周りで1次まで展開すると，

$$
  U\simeq 1+ \ri\theta^i T_i
$$

と書ける．ユニタリーである条件から，

$$
  1\simeq  (1-\ri \theta^i T_i^\dag) (1+\ri \theta^j T_j)\simeq 1-\ri\theta^i(T_i^\dag-T_i)
$$

より，$T_i^\dag = T_i$ が成り立つ．また，
で行列式が $1$ になる条件から，$1=\det U\simeq \det(1+ \ri \theta^iT_i)\simeq 1+\ri \theta^i \tr T_i$ より，
$\tr T_i=0$ がわかる．

$\det(1+ \ri \theta^iT_i)\simeq 1+\ri \theta^i \tr  T_i$ は，行列式の中で非対角成分を含むものは，
非対角成分の2次以上になる．したがって，$O(\theta)$ には，寄与しない．

次に，$e^{ X} e^{ Y} e^{- X}$ を考える．ここで，$X=\ri\theta^iT_i$, $Y=\ri\theta'^i T_i$ とする．
これは，$X$, $Y$ の2次までで，

$$
  \begin{split}
  e^{ X}e^{ Y}  e^{- X}&\simeq (1+X+\frac{X^2}{2})e^{ Y}(1-X+\frac{X^2}{2})=e^{ Y}+[X,e^{ Y}]+\frac{1}{2}[X,[X,e^{ Y}]]+\cdots\\
  &\simeq 1+Y+[X,Y]+\frac{Y^2}{2}+\cdots
  \end{split}
$$

となる．ここで，$[X,Y]=XY-YX$ は交換子である．$e^{ X} e^{ Y} e^{- X}$ も当然 $\mathrm{U}(N)$ の元になっているので，

$[T_i,T_j]= \ri f_{~ij}^{k}T_k$ となる必要がある．ここで，$\ri f_{~ij}^{k}$ は構造定数と呼ばれる．
$$
  \tr  T_iT_j = \frac{1}{2}g_{ij}
$$

とし，この逆行列を $g^{ij}$ とする．これを用いて，$f_{ijk}=f_{~ij}^{l}g_{lk}$ と定義すると，$f_{ijk}$ は完全反対称テンソルである．
適当に基底を選ぶと $g_{ij}=\delta_{ij}$ に取れる．
Jacobi恒等式

$$
  [T_i,[T_j,T_k]]+[T_j,[T_k,T_i]]+[T_k,[T_i,T_j]]=0
$$

より，構造定数は，

$$
  f^m_{~il}f^l_{~jk}+f^m_{~jl}f^l_{~ki}+f^m_{~kl}f^l_{~ij}=0
$$ {#eq-Jacobi}

を満たす．
$[T_i]^j_k=\ri f^{j}_{~ik}$ という行列を考えると，式 (@eq-Jacobi) より
$[T_i,T_j]=\ri f^{k}_{~ij}T_{k}$ を満たすことがわかる．これは随伴表現と呼ばれる．

::: example
**$\mathrm{SU}(2)$群**
  $T_i^\dag=T_i$で，$\tr T_i=0$となる，$2\times 2$行列は，$3$つあり，これは\textrm{Pauli}行列である:
  \begin{align}
    \sigma_1 = 
    \begin{pmatrix}
      0 & 1\\
      1 & 0
    \end{pmatrix},\quad
    \sigma_2 = 
    \begin{pmatrix}
      0 & -\ri\\
      \ri & 0
    \end{pmatrix},\quad
    \sigma_3 = 
    \begin{pmatrix}
      1 & 0\\
      0 & -1
    \end{pmatrix}.
  \end{align}
  \textrm{Pauli}行列は，$\tr \sigma_i\sigma_j = 2\delta_{ij}$に規格化されている．
  したがって，規格化因子を考慮して$T_i=\sigma_a/2$に取ると，
  $[T_i,T_j]=\ri\epsilon_{ijk}T_k$ の代数を満たす．$\epsilon_{ijk}$は完全反対称テンソルで，$\epsilon_{123}=1$に符号を取ってある．
:::

::: example
**$\mathrm{SU}(3)$群**

  \textrm{QCD}で重要になる$\mathrm{SU}(3)$群を考えよう．これは，3次元複素ベクトルの内積を不変にする変換である．
  $T_i^\dag=T_i$ で，$\tr T_i=0$ となる，$2\times 2$ 行列は8つある．したがって生成子は，
  \textrm{Gell-Mann}行列

$$
  \begin{split}
    &\lambda_1 = \begin{pmatrix}
      0 & 1 & 0\\
      1 & 0 & 0\\
      0 & 0 &  0
    \end{pmatrix},\quad
    \lambda_2 = \begin{pmatrix}
      0 & -\ri & 0\\
      \ri & 0 & 0\\
      0 & 0 &  0
    \end{pmatrix},\quad
    \lambda_3 = \begin{pmatrix}
      1 & 0 & 0\\
      0 & -1 & 0\\
      0 & 0 &  0
    \end{pmatrix},\quad
    \lambda_4 = \begin{pmatrix}
      0 & 0 & 1\\
      0 & 0 & 0\\
      1 & 0 &  0
    \end{pmatrix},\notag\\
    &\lambda_5 = \begin{pmatrix}
      0 & 0 & -\ri\\
      0 & 0 & 0\\
      \ri & 0 &  0
    \end{pmatrix},\quad
    \lambda_6 = \begin{pmatrix}
      0 & 0 & 0\\
      0 & 0 & 1\\
      0 & 1 &  0
    \end{pmatrix},\quad
    \lambda_7 = \begin{pmatrix}
      0 & 0 & 0\\
      0 & 0 & -\ri\\
      0 & \ri & 0
    \end{pmatrix},\quad
    \lambda_8 = \frac{1}{\sqrt{3}}\begin{pmatrix}
      1 & 0 & 0\\
      0 & 1 & 0\\
      0 & 0 &  -2
    \end{pmatrix}.
  \end{split}
$$

  を用いて，$T_i=\lambda_i/2$である．
  $[T_i,T_j]=\ri f^k_{~ij}T_k$でゼロでないものは，
   $f_{123}=1$,  $f_{458}=f_{678}={\sqrt{3}}/{2}$, $f_{147}=f_{165}=f_{246}=f_{257}=f_{345}=f_{376}=1/2$である．

:::

これまで$\mathrm{SU}(N)$群の生成子は，$N\times N$行列を用いて定式化したが抽象化して$[T_i,T_j]= \ri f_{~ij}^{k}T_k$を満たすものとして
リー群を定義する．


## Haar測度 {#sec-Haar_measure}
<!-- \subsection{Haar測度}\label{sec-Haar_measure} -->
群上で関数の積分を行うには，群構造と両立する自然な測度を導入する必要がある．特に，$\mathrm{SU}(2)$ のような連続群においては，離散的な和に代わる操作として，群の左右変換に対して不変な測度が求められる．このような測度は一般にHaar測度と呼ばれ，任意のコンパクト群に対して，定数倍を除いて一意に定まる．
Haar測度は，群の元 $g\in G$ に対し，
$$
    \int_G \dd{g} f(g)= \int_G \dd{g} f(hg)= \int_G \dd{g} f(gh)
$$
を満たす測度である．
ここで，$f(g)$ は，群の元 $g$ に依存する関数である．
この条件は，測度が群の左・右作用に対して不変であること，すなわち群の構造に依存しない自然な積分を定めることを意味する．
本稿では，
$$
    \int_G \dd{g}  = 1
$$
となるように正規化されたものを用いる．

具体的に $\mathrm{SU}(2)$ の場合に見ていこう．
$\mathrm{SU}(2)$ の元を
$$
    g= \cos\frac{\theta}{2}+\ri \symbf{\sigma}\cdot\bm{n}\sin\frac{\theta}{2}
$$
と表す(式 (@eq-SU2_n))．
$\bm{n}\in S^2$で，極座標表示 (@eq-n_polar) を用いると，Haar測度は，
$$
    \dd g =
    \frac{\dd{\theta}}{\pi} \sin^2\frac{\theta}{2} \frac{\dd{\Omega}}{4\pi}
$$
となる．ここで，$\dd\Omega$ は，$S^2$ の測度で，
$$
\dd\Omega=\sin\psi \dd\psi \dd\varphi
$$
である．パラメータは，$0\leq\theta\leq 2\pi$, $0\leq\psi\leq \pi$, $0\leq\varphi\leq 2\pi$ を取る．


## 中心
<!-- \subsection{中心} -->

群 $G$ の**中心**とは，群の元 $g\in G$ であって，任意の元 $h\in G$ に対し
$$
  hg=gh
$$
を満たすものの集合をいう．群 $G$ の中心を $Z(G)$ と表す:
$$
  Z(G)=\{g\in G\mid \forall h\in G,\; hg=gh\}.
$$

$Z(G)$ も群(アーベル群)をなす．
$\mathrm{SU}(2)$ の場合は，すべての元と可換な元は単位行列に比例するので，$\omega\mathbf{1}_2$
の形をとる．ユニタリ行列である条件から $|\omega|^2=1$ が得られ，行列式が $1$ である条件から，
$\omega^2=1$ が得られる．これを満たす $\omega$ は，$1,-1$ である．したがって，$\mathrm{SU}(2)$ の中心は，
$$
  Z(\mathrm{SU}(2))=\{ \mathbf{1}_{2},-\mathbf{1}_2\}\simeq \mathbb{Z}_2
$$
となる．
中心は，物質場を含まないゲージ理論においては，閉じ込め，非閉じ込め相を区別する高次対称性と関係する．

## 共役類
<!-- \subsection{共役類} -->
群 $G$ において，$2$ つの群の元 $g,g'\in G$ が，ある $h\in G$ を用いて，
$$
  g'=hgh^{-1}
$$
と表されるとき，$g$ と $g'$は\textit{共役}であるという．
このとき，$g$ と $g'$ は\textit{同じ\textit{共役類}に属する}という．
$g$ の\textit{共役類}を $\mathcal{C}_g$ と表す:
$$
  \mathcal{C}_g\coloneqq\{hgh^{-1}\mid h\in G\}.
$$

$G=\mathrm{SU}(2)$ の場合，$hgh^{-1}$ によって，$g$ を対角化できるので，$g$ として対角行列を考えれば良い．対角行列は，
$$
  e^{\ri\theta T_3}=\begin{pmatrix}
    e^{\ri\theta/2} & 0\\
    0 & e^{-\ri\theta/2}
  \end{pmatrix}
    \label{eq-representative_SU2}
$$
と表される．さらに，
$$
  \ri X=\ri \sigma_1= 
  \begin{pmatrix}
    0 & 1\\
    1 & 0
  \end{pmatrix}
$$
を用い，$(\ri X)^{-1}=-\ri X$ に注意して，
$$
  \ri X\begin{pmatrix}
    e^{\ri\theta/2} & 0\\
    0 & e^{-\ri\theta/2}
  \end{pmatrix}(\ri X)^{-1}
  =  
  \begin{pmatrix}
    e^{-\ri\theta/2} & 0\\
    0 & e^{\ri\theta/2}
  \end{pmatrix}
$$
となることがわかる．つまり，$\theta$ と $-\theta$ は共役となるので，
$\theta$ は，$0$ から $2\pi$ までの範囲を動くと考えることができる．
以下では，共役類のラベルとして $\mathcal{C}_\theta$ の表記を用いる．
$\theta=0$ および $2\pi$ に対応する行列は，すべての元と可換であり，中心に属する．したがって，
$$ \begin{aligned}
    \mathcal{C}_0&= \{\mathbf{1}_2\},\\
    \mathcal{C}_{2\pi}&= \{-\mathbf{1}_2\}.
 \end{aligned}
 $$

$0<\theta<2\pi$ の場合，共役類は，

$$
\mathcal{C}_{\theta}=\left\{\mathbf{1}_2\cos\frac{\theta}{2}+\ri\bm{n}\cdot \symbf{\sigma}\sin\frac{\theta}{2}\left|\bm{n}\in S^2\right.\right\}
$$
と書ける．

<!-- %  \subsection{中心化群}
% 群の元の$h\in G$と可換な群の元の集合は，中心化群(Centralizer)と呼ばれる．
%  $$
%      \mathrm{C}_G(h)\coloneqq\{g\in G|gh=hg\}
%      \label{eq-Centralizer}
%  $$
%  中心の元$z\in {Z}(G)$関しては，$\mathrm{C}_G(z)=G$となる．

%  $\mathrm{SU}(2)$の場合は，中心については，
%  $$
%       \mathrm{C}_G(\mathbf{1}_2)=\mathrm{C}_G(-\mathbf{1}_2)=\mathrm{SU}(2)
%  $$
%  $h=\exp\ri\theta T_3$については，
%  $$
%      C_{\mathrm{SU}(2)}(e^{\ri\theta T_3})=\{ e^{\ri\alpha T_3}|0\leq \alpha<4\pi\}\simeq \mathrm{U}(1)
%  $$
%  となる． -->


## 指標
<!-- \subsection{指標} -->
表現行列のトレースは指標と呼ばれる．
トレースの性質より，$h\in G$として，$\chi_a(g)=\chi_a(hgh^{-1})$ となることから，共役な元は，同じ指標の値を返すことがわかる．


$\mathrm{SU}(2)$ の表現 $j_a$ の指標は，
$$
\chi_a(g) =\tr_a D_{a}(g)
=\sum_{m_a} e^{\ri m_a\theta} = \frac{\sin\frac{\theta(2j_a+1)}{2} }{\sin\frac{\theta}{2}}
$$
と表される．ここで，$e^{\ri m_a\theta}$ は，$D_{a}(g)$ を対角化したときの固有値で，共役類のラベルに対応する．
このことから，$\chi_a(g)$ の代わりに，$\chi_a(\theta)$ と書くこともある．

\paragraph{指標の直交性}

式 (@eq-su2-D-orthogonality)に示される表現の直交性より，
$$
  \int \dd{g} \chi^\dag_a(g) \chi_b(g)=\delta_{ab}
$$
が成り立つ．指標は共役類のみに依存するため，測度 $\dd{\nu(\theta)}$ を導入することで，
$$
  \int \dd{\nu(\theta)}\chi^\dag_a(\theta) \chi_b(\theta)=\delta_{ab}
$$ {#eq-character_orthogonality}
という形で表すことができる．
ここで，$\dd{\nu(\theta)}$は，
$$
    \dd{\nu(\theta)}\coloneqq\frac{\dd\theta}{\pi}\sin^2\frac{\theta}{2}
$$
で与えられる共役類上の規格化された測度である．

さらに，
$$
\sum_{a} \chi^\dag_a(\theta) \chi_a(\theta')=\delta_\nu(\theta-\theta')
$$
が成り立つ．ここで $\delta_\nu(\theta-\theta')$ は，次を満たすデルタ関数である:
$$
    \int \dd{\nu(\theta')} f(\theta')\delta_\nu(\theta-\theta')=f(\theta).
$$

$\mathrm{SU}(2)$の指標に，
$$
\Delta_\theta=\frac{\partial^2}{\partial\theta^2}+\frac{\cos\frac{\theta}{2}}{\sin\frac{\theta}{2}}\frac{\partial}{\partial\theta}
$$
を作用させると，次の固有値方程式が成り立つ事がわかる:
$$
-\Delta_\theta\chi_a(\theta)=C_2(a)\chi_a(\theta).
$$
ここで，$C_2(a)=j_a(j_a+1)$ は，2次のCasimir不変量である．

<!-- ## $\mathrm{SU}(2)$上のHilbert空間
$\mathrm{SU}(2)$上の複素関数$f$で，
$$
  \int \dd{g} f^*(g)f(g) < \infty
$$
を満たすものは，Hilbert空間をなす．
このヒルベルト空間は，$L^2(\mathrm{SU}(2))$と表される．


Dirac記法を導入すると，状態は，
$$
\ket{f} = \int dg f(g)\ket{g}
$$
の形で書け，$f(g)$は， $f(g)$は内積$\bra{g}\ket{f}$により，
$$
f(g) = \bra{g}\ket{f}
$$
と表される．
また，$\ket{g}$の内積は，以下のデルタ関数になる:
$$
  \begin{split}
    \bra{g}\ket{g'} = \delta_{g,g'}.
  \end{split}
$$ -->





## 類演算子
群の元 $h\in G$ に対応する演算子として $L^h$ を導入し，
$\ket{g}$に対して，
$$
  L^h\ket{g}=\ket{hg}
$$
と定義する．同様に，右作用を表す演算子 $R^h$ を
$$
  R^h\ket{g}=\ket{g\bar{h}}
$$
と定義する．ここで，$\bar{h}$ は，$h$ の逆元を表す．
$L^h$ は，群の左作用，$R^h$は 右作用を表しており，次の関係を満たす:
$$ \begin{aligned}
  L^{h}L^{h'}&=L^{hh'},\\
  R^{h}R^{h'}&=R^{hh'},\\
  L^hR^{h'}&=R^{h'}L^h.
 \end{aligned}$$

$L^{h}R^{h}$ を状態 $\ket{\psi}$ に作用させると
$$
  \begin{split}
    L^hR^{h}\ket{\psi}=\int dg \psi(g)\ket{hg\bar{h}}=
    \int dg \psi(\bar{h}gh)\ket{g}
  \end{split}
$$
となる．
<!-- %  $L^g\ket{h}=\ket{gh}$,
%  $R^g\ket{h}=\ket{h\bar{g}}$

%  $L^g U_a L^{\bar{g}}=D_a(\bar{g})U_a$, 

%  $R^g U_a R^{\bar{g}}=U_aD_a(g)$

%  $R^g=e^{\ri\theta^iR_a}$
%  $L^g=e^{-\ri\theta^iL_a}$
%  $$
%    \begin{split}
%      L^gR^g\ket{j,m,n}=[D_a(\bar{g})]^m_{m'}
%      [D_a(g)]^{n'}_{n}
%      \ket{j,m',n'}
%    \end{split}
%  $$ -->

共役類 $\mathcal{C}_\theta$ に属する元 $g$ にわたる左作用 $L^g$ の積分で定義される演算子
$$
    T_\theta = \int_{g\in \mathcal{C}_\theta} dg L^g
$$
は，すべての $L^h$ および$R^h$ と可換である．
このような演算子 $T_\theta$ を類演算子と呼ぶ．
ここでは左作用 $L^g$ を用いて定義したが，$R^g$ を使っても同様に定義できる．

$\mathrm{SU}(2)$の場合，群のすべての元と可換であるので，$T_\theta$ は
表現空間の基底 $\ket{j,m,n}$ を取ると，単位行列に比例する形で作用する．
したがって，
$$
    T_\theta = \sum_{j}c_jP_{j}
$$
ここで，$P_{j}$ は，$\mathcal{Q}^*_j\otimes \mathcal{Q}_j$ への射影演算子で，$c_j$ は係数関数である．
$T_\theta$に対して表現を取り，トレースとすると，係数 $c_j$ は
$$
c_j = \frac{1}{d_j}\chi_j(\theta)
$$
と計算される．
したがって、類演算子は次のように展開される：
$$
    T_\theta = \sum_{j}\frac{1}{d_j}\chi_j(\theta)P_{j}.
$$



指標の直交性 (@eq-character_orthogonality) を用いると，射影演算子 $P_j$ は，
$$
    P_j =  d_j\int_{0}^{2\pi}\dd{\nu(\theta)}\chi^\dag_j(\theta) T_\theta
$$ {#eq-projector}
と表すことができる．

#### 類演算子の積

$T_\theta$と$T_{\theta'}$ の積は，
$$
T_\theta T_{\theta'}
= \sum_{j}\frac{1}{d^2_j}\chi_j(\theta)\chi_j(\theta')P_j
$$
となる．
一方で，射影演算 $P_j$は，式 (@eq-projector) により $T_{\theta''}$ を使って表されるので，
$$
T_\theta T_{\theta'}
=\int_{0}^{2\pi}\dd{\nu(\theta'')}
\mathcal{K}(\theta,\theta',\theta'') T_{\theta''}
$$
と書くことできる．
ここで，結合係数（structure constant）$\mathcal{K}(\theta, \theta', \theta'')$ は

$$
  \begin{split}
   \mathcal{K}(\theta,\theta',\theta'')= \sum_{a}\frac{1}{d_a}\chi_a(\theta)\chi_a(\theta')\chi^\dag_a(\theta'')
  \end{split}
$$

である．この関数は，$\theta''$ が $|\theta-\theta'|\leq \theta''\leq\min(\theta+\theta',4\pi-\theta-\theta')$ のときに値(台)を持つ．その上では次のように具体的に計算される:

$$
  \begin{split}
   \mathcal{K}(\theta,\theta',\theta'')
   =\frac{\pi}{4}\frac{1}{\sin\frac{\theta}{2}\sin\frac{\theta'}{2}\sin\frac{\theta''}{2}}.
  \end{split}
$$


<!-- %  Racah係数$W(abcd;ef)$を用いて，
%  $$
%    % \braket{ j_a (j_bj_c)j_{f};j_d,m_d}{(j_aj_b)j_{e}j_c;j_d,m_d}
%    [F_{abc}^d]_f^e=v_{e}v_{f}W(j_aj_bj_dj_c;j_{e}j_{f})
%  $$
%  と表せる．Wigner $6$-jシンボルを用いると
%  $$
%    W(abcd;ef)=(-1)^{a+b+c+d}
%    \begin{Bmatrix}
%      a & b & e\\
%      d & c & f
%    \end{Bmatrix}
%    % checked sympy 
%  $$ -->


<!-- %  $$
%    \begin{split}
%      &\begin{Bmatrix}
%        j_a,j_b,j_c\\
%        j_d,j_e,j_f
%      \end{Bmatrix}\\
%      &=\sum_{m_a}(-1)^{\sum_{k}(j_k-m_k)}
%      \begin{pmatrix}
%        j_a & j_b & j_c\\
%        -m_a & -m_b & -m_c
%      \end{pmatrix}
%      \begin{pmatrix}
%        j_a & j_e & j_f\\
%        m_a & -m_e & m_f
%      \end{pmatrix}
%      \begin{pmatrix}
%        j_d & j_b & j_f\\
%        m_d & m_b & -m_f
%      \end{pmatrix}
%      \begin{pmatrix}
%        j_d & j_e & j_c\\
%        -m_d & m_e & m_c
%      \end{pmatrix}.          
%    \end{split}
%  $$ -->




<!-- ## $S_3$群 {#sec-S3}

$S_3$は，3次の対称群で，正三角形の合同群である．
正三角形の合同群の元は$120^\circ$回転$\sthreer$, $240^\circ$回転$\sthreer^2 = \sthreer^{-1}$, 及び，各頂点を通る軸の反転$s_i$($i=1,2,3$)の$6$つからなる．
置換群との対応は，
\begin{align}
&e=\begin{pmatrix}
1 & 2 & 3  \\
1 & 2 & 3 
\end{pmatrix}=(),\quad
\sthreer=\begin{pmatrix}
1 & 2 & 3  \\
2 & 3 & 1 
\end{pmatrix}=(123),\quad
\sthreerr=\begin{pmatrix}
1 & 2 & 3  \\
3 & 1 & 2 
\end{pmatrix}=(132),\notag\\
&\sthreera=\begin{pmatrix}
1 & 2 & 3  \\
1 & 3 & 2 
\end{pmatrix}=(23),\quad
\sthreerb=\begin{pmatrix}
1 & 2 & 3  \\
3 & 2 & 1
\end{pmatrix}=(13),\quad
\sthreerc=\begin{pmatrix}
1 & 2 & 3  \\
2 & 1 & 3 
\end{pmatrix}=(12)
\end{align}
である．%$\sthreerc \sthreer \sthreerc=\sthreerr$.
元の合成は，例えば $\sthreerc\sthreer = \sthreera$や$\sthreerc\sthreerr = \sthreerb$のようになる．他の積は表\ref{table:S3}にまとめてある．
\begin{table}[htbp]
  \centering
  \begin{tabular}{|c||c|c|c|c|c|c|} \hline
    $\circ$ &  $e$& $\sthreer$ & $\sthreerr$  & $\sthreera$ & $\sthreerb$ & $\sthreerc$   \\ \hline \hline
    $e$ &  $e$& $\sthreer$ & $\sthreerr$  & $\sthreera$ & $\sthreerb$ & $\sthreerc$   \\ \hline
     $\sthreer$ &  $\sthreer$& $\sthreerr$ & $e$  & $\sthreerc$ & $\sthreera$ & $\sthreerb$   \\ \hline
     $\sthreerr$ &  $\sthreerr$& $e$ & $\sthreer$  & $\sthreerb$ & $\sthreerc$ & $\sthreera$   \\ \hline
     $\sthreera$ &  $\sthreera$& $\sthreerb$ & $\sthreerc$  & $e$ & $\sthreer$ & $\sthreerr$   \\ \hline
     $\sthreerb$ &  $\sthreerb$& $\sthreerc$ & $\sthreera$  & $\sthreerr$ & $e$ & $\sthreer$   \\ \hline
     $\sthreerc$ &  $\sthreerc$& $\sthreera$ & $\sthreerb$  & $\sthreer$ & $\sthreerr$ & $e$   \\ \hline
  \end{tabular}
  \caption{$\mathrm{S}_3$群の積表．}
  \label{table:S3}
\end{table}
%群$G$の元$a,b\in G$について$a = g b g^{-1}$となる単位元でない$g$の元が存在する時，$a$と$b$は共役という．
%$a$に共役な元の集合を$a$の共役類という．群の元は互いに共役な元事に集めて類別できる．
%共役類を見るために，群の掛け算表の右から群の元を掛けて
共役類は，
\begin{align}
\mathcal{C}_1 = \{e\},\quad \mathcal{C}_2 = \{\sthreera, \sthreerb, \sthreerc\}, \quad \mathcal{C}_3 = \{\sthreer, \sthreerr\}.
\end{align}
の$3$種類ある．共役類の積は，
\begin{table}[h]
  \centering
  \caption{$\mathrm{S}_3$の共役演算表．}
  \begin{tabular}{c|c c c c c c}
       & $e$ & $\sthreer$ & $\sthreerr$ & $\sthreera$ & $\sthreerb$ & $\sthreerc$ \\
      \hline
      $e$          & $e$          & $e$       & $e$  & $e$ & $e$ & $e$ \\
      $\sthreer$        & $\sthreer$        & $\sthreer$  & $\sthreer$         & $\sthreerr$ & $\sthreerr$ & $\sthreerr$ \\
      $\sthreerr$   & $\sthreerr$   & $\sthreerr$          & $\sthreerr$        & $\sthreer$  & $\sthreer$ & $\sthreer$ \\
      $\sthreera$   & $\sthreera$   & $\sthreerb$  & $\sthreerc$  &$\sthreera$   & $\sthreerc$  & $\sthreerb$ \\
      $\sthreerb$   & $\sthreerb$   & $\sthreerc$  & $\sthreera$  & $\sthreerc$ & $\sthreerb$        & $\sthreera$      \\
      $\sthreerc$   & $\sthreerc$   & $\sthreera$  & $\sthreerb$  & $\sthreerb$      & $\sthreera$ & $\sthreerc$        \\
  \end{tabular}
  \label{table:S3}
\end{table}
中心化群 ($\mathrm{C}_{S_3}(s) = \{g\in G| sg=gs \text{ for all } s\in G \}$) of the representative of a conjugacy class are
\begin{align}
\mathrm{C}_{S_3}(\mathcal{C}_1) &= \mathrm{S}_3,\\
\mathrm{C}_{S_3}(\mathcal{C}_2) &= \{e,\sthreera\},\\
\mathrm{C}_{S_3}(\mathcal{C}_3) &= \{e,\sthreer,\sthreerr\}=\mathbb{Z}_3.
\end{align}

\begin{align*}
\rho_{A_1} &\equiv \rho^{(1)} \quad\text{(trivial)} \\
\rho_{A_2} &\equiv \rho^{(1')} \quad\text{(sign)} \\
\rho_E     &\equiv \rho^{(2)} \quad\text{(standard)}
\end{align*}

We define the class operators as $T_i = \sum_{g \in \mathcal{C}_i} g$. 
The products of these operators give the fusion rules of the conjugacy classes. 
The products of the conjugacy classes are summarized in Table \ref{table:S3 conjugacy class}.
\begin{table}[htbp]
  \centering
  \begin{tabular}{|c||c|c|c|} \hline
    &  $T_1$& $T_2$ & $T_3$\\ \hline\hline
    $T_1$ &  $T_1$& $T_2$ & $T_3$\\ \hline
    $T_2$&  $T_2$& $3T_1+3T_3$ & $2T_2$\\ \hline
    $T_3$ &  $T_3$& $2T_2$ & $2T_1+T_3$\\ \hline
  \end{tabular}
  \caption{Multiplication table of conjugacy class of $\mathrm{S}_3$}
  \label{table:S3 conjugacy class}
\end{table}
\begin{table}[htbp]
  \centering
  \begin{tabular}{|c||c|c|c|} \hline
    $\otimes$ &  $A_1$& $A_2$& $E$ \\ \hline\hline
    $A_1$ &  $A_1$& $A_2$& $E$ \\ \hline
    $A_2$ &  $A_2$& $A_1$& $E$ \\ \hline
    $E$&  $E$& $E$& $A_1\oplus A_2\oplus E$ \\ \hline
  \end{tabular}
  \caption{Multiplication table of representation of $\mathrm{S}_3$}
  \label{table:S3 representation}
\end{table}

\begin{table}[htbp]
  \centering
  \begin{tabular}{|c|c|c|c|c|} \hline
     &  $d_a$ & $T_1$& $T_2$& $T_3$ \\ \hline\hline
    $A_1$ &  1& $1$& $1$& $1$ \\ \hline
    $A_2$ &  1& $1$& $-1$& $1$ \\ \hline
    $E$&     2& $2$& $0$& $-1$ \\ \hline
  \end{tabular}
  \caption{character of $\mathrm{S}_3$}
  \label{table:S3 character}
\end{table}


$\mathrm{S}_3$ has three unitary representations. These are two one-dimensional representations (the trivial representation $A_1$ and the $A_2$ representation) and one two-dimensional representation $E$. Specifically, $A_1$ is trivial for all $g \in \mathrm{S}_3$, i.e., $D_{A_1}(g) = 1$. For $A_2$, we have $D_{A_2}(g) = 1$ for $g \in \{e, \sthreer, \sthreerr\}$, and $D_{A_2}(g) = -1$ for $g \in \{\sthreera, \sthreerb, \sthreerc\}$.
The two-dimensional representation $E$ is given by the matrices:
$$
\begin{split}
D_{E}(e) &= \begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix},\quad
D_{E}(\sthreer) = \begin{pmatrix}
c & -s\\
s & c
\end{pmatrix},
\quad
D_{E}(\sthreerr) = \begin{pmatrix}
c & s\\
-s & c
\end{pmatrix},\\
D_{E}(\sthreera) &= \begin{pmatrix}
1 & 0\\
0 & -1
\end{pmatrix},\quad
D_{E}(\sthreerb) = \begin{pmatrix}
c & -s\\
-s & -c
\end{pmatrix},\quad
D_{E}(\sthreerc) = \begin{pmatrix}
c & s\\
s & -c
\end{pmatrix}.
\end{split}
$$
Here, $c=\cos(2\pi/3)=-1/2$, $s=\sin(2\pi/3)=\sqrt{3}/2$.
The tensor product of representations can be taken, and it decomposes into a direct sum. For example, 
$\rho_E \otimes \rho_E = A_1 \oplus A_2 \oplus E$.
Table \ref{table:S3 representation} summarizes the decomposition of the tensor product of representations.


\begin{align}
T_1& = e\\
T_2 &= \sthreera+\sthreerb+\sthreerc,\\
T_3 &= \sthreer+\sthreerr.
\end{align}


\begin{align}
D_E(T_1) &= I_2\\
D_E(T_2) &= 0,\\
D_E(T_3) &= -I_2.
\end{align}


\begin{align}
D_{A_1}(T_1) = 1\\
D_{A_1}(T_2) = 3,\\
D_{A_1}(T_3) = 2.
\end{align}

\begin{align}
D_{A_2}(T_1) &= 1\\
D_{A_2}(T_2) &= -3,\\
D_{A_2}(T_3) &= 2.
\end{align}


$$
  \begin{split}
    \frac{|c_g|}{d_a}\chi_a(g) 1_a
  \end{split}
$$ -->