---
title: "序文"
---
本講義ノートは，「原子核三者若手 夏の学校2025」における講義「ハミルトニアン形式による格子ゲージ理論入門」のノートである．
本講義では，格子ゲージ理論のハミルトニアン形式に焦点を当て，その基礎的枠組みと物理的意味を解説する．

::: {.callout-collapse title="クリックで開閉"}
ここに折りたたみの中身を書きます。
:::

# 格子ゲージ理論の概要

本講義ノートでは，格子上に構成された非可換ゲージ理論のハミルトニアン形式の基礎的事項について解説する．
ハミルトニアン形式では，ヒルベルト空間とその上の物理状態を扱う．
ゲージ理論の物理的状態はゲージ不変な状態である．つまり，物理状態はGaussの拘束条件（Gauss's law constraint）を満たす必要がある．連続場の理論では，一般にこの拘束条件を解くのは困難であるが，格子上では形式的に拘束条件を解くことが可能となる．この拘束条件を満たす状態は，ストリングネットやスピンネットワークと呼ばれる．
ストリングネット間の演算はトポロジカル秩序相を記述する代数的構造(modular tensor category)を満たすことが知られている．
ストリングネットの基底を用いることで、ゲージ不変なヒルベルト空間を明示的に構成することができる．さらに，この基底におけるハミルトニアンの作用は，電場項を加えたストリングネット模型のハミルトニアンとなる．
本講義では，格子上(より一般的にグラフ上)でのゲージ理論の定式化から出発し，それを変形，正則化していくことでスピン模型であるストリングネット模型に帰着する過程を示す．スピン模型による記述を通じて，量子コンピュータやテンソルネットワークを用いた手法が適用しやすくなることが期待される．
<!-- 
講義の後半では，解析手法の例として，$(2+1)$次元の$\mathrm{SU}(3)$ゲージ理論を変分波動関数を用いた解析手法を紹介する．

本講義ノートでは，Einstein記法を用いる．つまり上下に現れた同じ添字に対しては，断りが無い限り縮約（和を取る）を行うものとする．また，状態のテンソル積$\ket{a}\otimes \ket{b}$は，単に$\ket{a}\ket{b}$のように表記する．
$\mathbb{Z}$，$\mathbb{R}$，$\mathbb{C}$は，整数,
実数および複素数の集合を表す．
ノートの最新版は，\href{https://ribf.riken.jp/~hidaka/yh/slide/hamiltonian_summerschool.pdf}{https://ribf.riken.jp/\textasciitilde hidaka/yh/slide/hamiltonian\_summerschool.pdf}よりダウンロードできる．
本講義ノートには，誤植や致命的な誤りが含まれている可能性がある点について，あらかじめご了承ください． -->