# 量子群による有限次元近似　{#sec-cutoff_representation}
一般に$\mathrm{SU}(N)$の既約表現は無限に存在するため，有限の格子上であってもHilbert空間は無限次元である．
量子計算機などで数値計算するためには有限次元のHilbert空間に近似する必要がある．
ここでは，ひとつの有効な方法として，量子群変形を用いた有限次元近似法を紹介する[@Zache:2023dko,@Hayata:2023puo]．
量子群$\mathrm{SU}(N)_k$では，Young図の横方向の箱の数の最大値が$k$となる．
例えば，$\mathrm{SU}(2)_k$の場合は，スピン$j$が$0,1/2,1,\cdots, k/2$の値に制限される．
量子群変形の利点は，これまでに導入した式 (@eq-partition) や (@eq-Fmove) が形式的にはそのまま成り立つ点である．
ただし，係数が変形される．
量子群の詳細は割愛し(@sec-q_deformation 節参照)，ここでは，$\mathrm{SU}(2)_k$ と $\mathrm{SU}(3)_k$ の場合について紹介する．

## $\mathrm{SU}(2)_k$
表現のカットオフにより，式 (@eq-fusion_delta) の $\delta_{abc}$ は修正され

$$
  N_{ab}^c=\delta_{abc}\coloneqq \begin{cases}
  1 &
  j_{a}+j_{b}\geq j_{c},
  j_{b}+j_{c}\geq j_{a},
  j_{c}+j_{a}\geq j_{b},
  j_{a}+j_{b}+j_{c}\in\mathbb{Z},\\
  &\text{かつ } j_a+j_b+j_c\leq k
  \\
  0 & \text{その他}
  \end{cases}
$$ {#eq-fusion_q}

となる．表現の次元だった $d_a$ は，量子次元(Frobenius-Perron dimension)と呼ばれ，

$$
    [N_a]^{c}_{b}=N_{ab}^c
$$ {#eq-N_matrix}

を行列 $N_{a}$ と見た時の最大固有値で与えられる．これは，パラメータ

$$
  q = \exp\ri \frac{2\pi}{k+2}
$$

を用いて，

$$
  [n]\coloneqq  \frac{q^{\frac{n}{2}}-q^{-\frac{n}{2}}}{q^{\frac{1}{2}}-q^{-\frac{1}{2}}}=\frac{\sin\qty(\frac{\pi}{k+2}n)}{\sin\qty(\frac{\pi}{k+2})}
$${#eq-n}

を定義すると，$d_a=[2j_a+1]$となることが知られている．カットオフ無限大 $k\to\infty$ では，
$d_a=2j_a+1$ に帰着する．

\begin{question}
  $k=1,2$ の場合に具体的に量子次元を計算し，表現 $j$ の量子次元が $[j+1]$ なることを確かめよ．
\end{question}

全量子次元は，

$$
  \mathcal{D} \coloneqq \sqrt{\sum_{a}d_a^2}=\sqrt{\frac{k+2}{2}}\frac{1}{\sin\qty(\frac{\pi}{k+2})}
$$

と定義される．$k$ が大きい場合に $\mathcal{D}\sim (k+2)^{3/2}$ と振る舞う．
また，2次の Casimir 不変量は $C_2(a)=[j_a][j_a+1]$ となる．

Wilsonループの作用を計算するためには $F$-symbol が必要であった．
これは，式 (@eq-fmoves) と同様に

$$
  [F^{abc}_d]_{ef}=(-1)^{j_a+j_b+j_c+j_d}\sqrt{d_{e}d_{f}}
  \begin{Bmatrix}
    j_a & j_b & j_e\\
    j_c & j_d & j_f
  \end{Bmatrix}
$$

と表せる．
ただし，Wigner $6$-$j$ シンボルは，

$$
  \begin{split}
    \begin{Bmatrix}
      a & b & c\\
      d & e & f
    \end{Bmatrix}
    &\coloneqq \Delta(a,b,c)\Delta(a,e,f)\Delta(d,b,f)\Delta(d,e,c)\sum_z(-1)^z [z+1]!\\ 
    &\quad\times \frac{([a+b+d+e-z]![a+d+c+f-z]![b+e+c+f-z]!)^{-1}}{[z-a-b-c]![z-a-e-f]![z-d-b-f]![z-d-e-c]!}
  \end{split}
$$

と修正される．ここで，

$$
  \Delta(a,b,c)=\delta_{abc}\sqrt{\frac{[a+b-c]![a-b+c]![-a+b+c]!}{[a+b+c+1]!}}\,,
$$

および，$[n]!=[n][n-1]\cdots [2][1]$である．
また，$z$ が取りうる範囲は，

$$
  \max(a+b+c,a+e+f,d+b+f,d+e+c)\leq z\leq 
  \min(a+b+d+e,a+d+c+f,b+e+c+f)
$$
である．

## $\mathrm{SU(3)}_k$

$\mathrm{SU}(3)_k$ の表現は，Dynkin ラベル $a=(p_a,q_a)$ で表される．
fusion の多重度は，
$$
  N_{ab}^{c} =(k_0^{\max}-k_0^{\min}+1)\delta_{ab}^c
$$
で与えられる [@Begin:1992rt].
ここで，
$$
  k_0^{\min}=\max(p_a+q_a,p_b+q_b,p_c+q_c,\mathcal{A}-\min(p_a,p_b,q_c),\mathcal{B}-\min(q_a,q_b,p_c))\,,
$$
$$
  k_0^{\max}=\min(\mathcal{A},\mathcal{B})\,,
$$

$$
  \mathcal{A}=\frac{1}{3}\qty(2(p_a+p_b+q_c)+q_a+q_b+p_c)\,,
$$

$$
  \mathcal{B}=\frac{1}{3}\qty(p_a+p_b+q_c+2(q_a+q_b+p_c))\,,
$$

$$
  \delta_{ab}^c=\begin{cases}
    1\quad \text{if $k_0^{\max}>k_0^{\min}$ and $\mathcal{A}, \mathcal{B}\in\mathbb{Z}_+$}\\
    0\quad\text{otherwise}
  \end{cases}
$$
である．$\mathbb{Z}_+$は非負の整数全体を表す．

$q$変形パラメータ
$$
  q = \exp(\ri\frac{2\pi}{k+3})
$$
を用いて，$q$数は，
$$
  [n]\coloneqq  \frac{q^{\frac{n}{2}}-q^{-\frac{n}{2}}}{q^{\frac{1}{2}}-q^{-\frac{1}{2}}}=\frac{\sin\qty(\frac{\pi}{k+3}n)}{\sin\qty(\frac{\pi}{k+3})}
  \label{eq-[n]su3}
$$
で定義される．$q$は，Dynkinラベルのではない点に注意.

$2$次のCasimir不変量 $C_2(a)$は，
$$
  C_2(a)  = \frac{1}{2}\qty(\left[\frac{p_a}{3}-\frac{q_a}{3}\right]^2+\left[\frac{2p_a}{3}+\frac{q_a}{3}+1\right]^2+\left[\frac{p_a}{3}+\frac{2q_a}{3}+1\right]^2-2)
$${#eq-C2_su3}
で与えられる [@Bonatsos:1999xj] \footnote{ここでの$C_2(a)$の規格化因子は[@Bonatsos:1999xj] の $1/2$ を採用している．}．

同様に，量子次元は，
$$
  d_{a} =\frac{1}{[2]}[p_a+1][q_a+1][p_a+q_a+2]
  \label{eq-dpq}
$$
となる [@Coquereaux:2005hu]．
もっとも重要なのは$F$-symbolsだが，残念ながらコンパクトな表式は知られていない．小さい$k$については，[@Ardonne2010ClebschGordanA6] で議論されている．


<!-- ## 線の向きについて
ある表現のWilson線の矢印の向きを反転させると，これは反表現に対応し，一般には区別される状態である．
しかし，$\mathrm{SU}(2)$の特殊性として，表現と反表現が同型であるという性質がある．この性質を考慮すると矢印の向きを忘れることができる．
具体的には，線と頂点の位相の再定義を使って，$d_a$が現れるところを$(-1)^{j_a}d_a$に置き換えることで，向きを忘れることができる． -->

