



<!-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%集中講義ではコメントアウト -->
### $e^{-\beta H}$ の評価

数値計算を行なう上で，しばしば$H$そのものを考えるのではなく，指数関数の上にのせた，$e^{-\ri t H}$ や，$e^{-\beta H}$ を考えるほうが便利なことがある．
ここでは，$e^{-\beta H}$ を評価する方法を考えよう．まず，

$$
  H_E=\frac{1}{2}\sum_{e\in E} E^2(e)\,,
$$

$$
  H_M=- K \sum_{f\in F} \tr U ( f)
$$

として，ハミルトニアンを $H=H_E+H_M$ に分解する．
次に $e^{-\beta H}$ を

$$
  e^{-\beta H} = \qty(e^{\delta H} )^N


と表す．ここで，$\delta =-\beta/N$ である．
$N$ が大きいとして，

$$
  e^{\delta H} = e^{\delta H_E}e^{\delta H_M}
   +\order{\delta^2}
$$

で近似する．これは鈴木-Trotter分解と呼ばれる．
$e^{\delta H_E}$ は，スピンネットワークの基底を取ると対角なため評価は容易である．
一方 $e^{\delta H_M}$ は，工夫が必要である．$e^{\delta H_M}$ は，

$$
  e^{\delta H_M} = \prod_{f\in F}e^{-\delta K \tr U(f)}
$$

と表せる．$\tilde{K}=-\delta K$ として，$\exp({\tilde{K}\tr U})$ を変形しよう．
これは，形式的に

$$
  \exp \qty(\tilde{K}\tr U)=\sum_{n=0}^\infty\frac{\tilde{K}^n}{n!}
  \qty(\tr U)^n
$$

と展開される．$n\geq1$ について，
$\qty(\tr U)^n$ は，式 (@eq-fusion_Wilson_loop) を用いると

$$
  \qty(\tr U)^n= \sum_{c}\tr U_c
  [(N_{\frac{1}{2}})^{n-1}]^{c}_{\frac{1}{2}}
  = \sum_{c,d}(\tr U_c)[(N_{\frac{1}{2}})^{-1}]^c_d
  [(N_{\frac{1}{2}})^{n}]^{d}_{\frac{1}{2}}
$$

と表すことができる．したがって，

$$
  \begin{split}
    \exp(\tilde{K}\tr U)
        &=\sum_{c,d}(\tr U_c)[(N_{\frac{1}{2}})^{-1}]^c_d \qty[\exp \tilde{K} N_{\frac{1}{2}}]^d_{\frac{1}{2}}  
    %&= 1+ \sum_{c,d}(\tr U_c)[(N_{\frac{1}{2}})^{-1}]^c_d\sum_{n=1}^\infty\frac{\tilde{K}^n}{n!}
  %[(N_{\frac{1}{2}})^{n}]^{d}_{\frac{1}{2}}
    %\\
    %&= 1-\sum_{c}(\tr U_c)[(N_{\frac{1}{2}})^{-1}]^c_{\frac{1}{2}}+ \sum_{c,d}(\tr U_c)[(N_{\frac{1}{2}})^{-1}]^c_d\sum_{n=0}^\infty\frac{\tilde{K}^n}{n!}
  %[(N_{\frac{1}{2}})^{n}]^{d}_{\frac{1}{2}}
    %\\
    %&=1+\sum_{c,d}(\tr U_c)[(N_{\frac{1}{2}})^{-1}]^c_d \qty[\exp \tilde{K} N_{\frac{1}{2}} -1]^d_{\frac{1}{2}}     
  \end{split}
$$

と表せる．
ここで $N_{\frac{1}{2}}$ は，
$$
  N_{\frac{1}{2}}=
    \begin{pmatrix}
    0 & 1 & 0 & \cdots & 0 \\
    1 & 0 & 1 & \ddots & 0 \\
    0 & 1 & \ddots & \ddots  & 0 \\
    \vdots & \ddots & \ddots & 0 & 1 \\
    0 & 0 & 0 & 1 & 0 
  \end{pmatrix}
$$

という3重対角行列である．

$N_{ab}^c$ は，Verlinde formula [@Verlinde:1988sn] を用いると，

$$
  N_{ab}^c = \sum_{d}\frac{S_{ad}S_{bd}S_{cd}^*}{S_{0d}}
$$

表すことができる．ここで，

$$
  S_{ab}= \sqrt{\frac{2}{k+2}}\sin\qty(\frac{(2j_a+1) (2j_b+1)\pi}{k+2})=\frac{1}{\mathcal{D}}[(2j_a+1)(2j_b+1)]
$$

である．
したがって，行列 $N_{\frac{1}{2}}$ (式 (@eq-N_matrix)を参照) は，固有値 $\lambda_a$ を
$$
  \lambda_a =  \frac{S_{\frac{  1}{2}a}}{S_{0a}}=2\cos\qty(\frac{(2j_a+1)\pi}{k+2})\,,\\
$$

($j_a=0,\cdots,k/2$)，固有ベクトルを $[u_a]^b=S_{ab}$ として，

$$
  N_{\frac{1}{2}}=\sum_{a}\lambda_au_a u_a^\dag
$$

と書ける．これを用いると，

$$
  \begin{split}
    \exp (\tilde{K}\tr U) &=\sum_{a}\sum_{b} \qty(\tr U_{b})[u_a]^b [u_a^\dag]_{\frac{1}{2}}\frac{e^{\tilde{K}\lambda_a}}{\lambda_a} \\
    &=  \sum_{b} \qty(\tr U_{b}) C^b(\tilde{K})
  \end{split}
$$

と表すことできる．ここで，係数は，

$$
  \begin{split}
    C^b(\tilde{K})&\coloneqq\sum_{a}\frac{2}{k+2}\sin\qty(\frac{(2j_a+1)(2j_b+1)\pi}{k+2})
    \sin\qty(\frac{2(2j_a+1)\pi}{k+2})
    \frac{e^{2\tilde{K}\cos\frac{(2j_a+1)\pi}{k+2}}}{2\cos\frac{(2j_a+1)\pi}{k+2}}\\
    &=\sum_{a}\frac{2}{k+2}\sin\qty(\frac{(2j_a+1)(2j_b+1)\pi}{k+2})
    \sin\qty(\frac{(2j_a+1)\pi}{k+2})e^{2\tilde{K}\cos\frac{(2j_a+1)\pi}{k+2}}
  \end{split}
$$

である．Wilsonループの状態への作用は，式 (@eq-Wilson_loop_action) によって定まっているので，この展開を用いると $e^{\delta H_M}$ の状態への作用が定まる．